# To Install Numpy

In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


***5 ways to make numpy array***

## 1) Numpy Array Using Python Stuctures i.e (List or Tuple or dict)

In [2]:
import numpy as np

# 1 D array

In [3]:
myarr=np.array([1,2,3,4,5,6,7,8])

In [4]:
myarr

array([1, 2, 3, 4, 5, 6, 7, 8])

***Too access each element of an array***

In [5]:
for i in myarr:
    print(i)

1
2
3
4
5
6
7
8


***Too access Speacific Index of array***

In [6]:
myarr[2]

3

***To know the shape of the array or how many rows and coloumns in an array***

In [7]:
myarr.shape

(8,)

***To Know the datatype of an array***

In [8]:
myarr.dtype

dtype('int32')

***To Create Array of our speacfic datatype only***

In [9]:
ae=np.array([1,2,3,4,5,6,7,8],np.int8)

In [10]:
ae


array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int8)

In [11]:
ae.dtype

dtype('int8')

***To Reshape the array or convert the array into differnt shape... As it is 1 D array***

In [12]:
ae.reshape([2,4])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int8)

***Note:-In reshape multiple should be of both number should be equal to number of element in the array***

# 2 Dimension array

In [13]:
arr=np.array([[1,2,3],[4,5,6]])

In [14]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
for i in arr:
    print(i)

[1 2 3]
[4 5 6]


In [16]:
arr[0,2]

3

***Convert into 1 D array***

In [17]:
arr.ravel()

array([1, 2, 3, 4, 5, 6])

In [18]:
a=arr.reshape([3,2])

In [19]:
a.shape

(3, 2)

***To Know The Size of an array***

In [20]:
a.size

6

# # 2) Intrinsic Numpy Array Creatioo Objects

***To Crate the array of zeoros***

In [21]:
zeros1=np.zeros((2,5))

In [22]:
zeros1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

***To create an array using arange function***

In [23]:
ran=np.arange((10))

In [24]:
ran

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

***It will create an array from  1 to 5 with 10 even differnce using linspace  ***

In [25]:
lp=np.linspace(1,5,10)

In [26]:
lp


array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

***Empty will create an array of matrix 4,6 with random elemnts in it later on we can change these values***

In [27]:
emp=np.empty((4,6))

In [28]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.86921143e-306, 8.90099485e-307, 6.23057349e-307],
       [8.45593934e-307, 7.56593017e-307, 1.11261027e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 7.56599128e-307,
        1.42417629e-306, 8.45593934e-307, 6.89805151e-307],
       [1.78022206e-306, 8.34451503e-308, 1.78022342e-306,
        8.06635958e-308, 1.42410974e-306, 1.69105613e-306]])

***It will create an new array using old array size and element i.e in simple words copy array*** 

In [29]:
emp_like=np.empty_like(lp)

In [30]:
emp_like

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

***It will reture matrix of 10 by 10 we can create array of matrix like this lateron we can assign values to it***

In [31]:
ide=np.identity(10)

In [32]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

***To Create An array of 1 and Default datatype is foat***

In [33]:
one=np.ones(8)

In [34]:
one

array([1., 1., 1., 1., 1., 1., 1., 1.])

***To Change the Data Type of an Array***

In [35]:
one.astype(int)

array([1, 1, 1, 1, 1, 1, 1, 1])

***To Know the dimesion of an array***

In [36]:
ad=np.array([[1,2,3],[4,5,6],[7,8,9]])


In [37]:
ad.ndim

2

***To know the size of an array***

In [38]:
ad.size

9

***To Know the Bytes used by an array or size of bytes taken by an array***

In [39]:
ad.nbytes

36

***To know the index number of the greatest element in an array***

In [40]:
ad.argmax()

8

***To know the index number of an mininum element in an Array***

In [41]:
ad.argmin()

0

In [42]:
ad.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [43]:
ag=np.array([[1,2,3],[4,5,6],[7,1,0]])
ag

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

***To find the index number of an maximum element in coloums***

In [44]:
ag.argmax(axis=0)

array([2, 1, 1], dtype=int64)

***To find the index number of an maximum element in rows***

In [45]:
ag.argmax(axis=1)

array([2, 2, 0], dtype=int64)

***Sum of an array by coloumns***

In [46]:
ag.sum(axis=0)

array([12,  8,  9])

***Sum of an array by rows***

In [47]:
ag.sum(axis=1)

array([ 6, 15,  8])

***To Transfer the data of coloumns into rows and rows into coloums using traspose***

In [48]:
ag.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

***To find the elements in an array which will return the index number of an array where  the element is present***

In [49]:
np.where(ag>3)

(array([1, 1, 1, 2], dtype=int64), array([0, 1, 2, 0], dtype=int64))

## Maths Operation on Array

In [50]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,8,7],[6,5,4],[3,2,1]])

In [51]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

***Each element should be of same shape to do maths operation on array***

In [53]:
a+b

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [54]:
a*b

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [55]:
a/b

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

# Matrix in Numpy

***To Create matrix in numpy***

***Two Ways to create numy matrix***


***1)By Using np.array function of 2 or 3 dimision***

***2)By using matrix function***

In [56]:
a=np.matrix("1,2;3,4")

In [57]:
a

matrix([[1, 2],
        [3, 4]])

***To find the inverse of an matrix***

In [58]:
b=np.linalg.inv(a)

In [59]:
b

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

***To Find the Vector Multiply of matrxi***

In [60]:
c=np.dot(a,a)

In [61]:
c

matrix([[ 7, 10],
        [15, 22]])

***To Multiply the matrix by itslef by 3 or anytime you want***

In [62]:
np.linalg.matrix_power(a,3)

matrix([[ 37,  54],
        [ 81, 118]])

***Vector Multiply of two matrix***

In [63]:
a1=np.matrix("1,2;3,4")
a2=np.matrix("5,6;7,8")

In [64]:
a1

matrix([[1, 2],
        [3, 4]])

In [65]:
a2

matrix([[5, 6],
        [7, 8]])

In [66]:
np.dot(a1,a2)

matrix([[19, 22],
        [43, 50]])

***To Find the Deteminat of array or matrix***

In [67]:
a7=np.matrix("1,2;3,4")

In [68]:
a7

matrix([[1, 2],
        [3, 4]])

In [69]:
d=np.linalg.det(a7)

In [70]:
d

-2.0000000000000004

***To Roundoff the value***

In [71]:
round(d)

-2.0

***To Solve Linear Equation***


***3x+2y=9***

***x+2=8***

In [72]:
a3=np.array([[3,1],[1,2]])
a4=np.array([9,8])

In [73]:
re=np.linalg.solve(a3,a4)

In [74]:
re

array([2., 3.])

***To Convert the float to int***

In [75]:
re.astype(int)

array([2, 3])